#!/bin/sh

echo "======================================================="
echo "======== Setting up Raspberry Pi WiFi AP Mode ========="
echo "======================================================="

####################################################################
#	copy configs to relevant directories
####################################################################

echo "[1/8] Configuring DHCP"
cp ./config-files/udhcpd_google.conf /etc/udhcpd.conf
cp ./config-files/udhcpd /etc/default      

echo "[2/8] Configuring interfaces"
cp ./config-files/interfaces /etc/network
cp ./config-files/interfaces.ap /etc/network
cp ./config-files/interfaces.client /etc/network
cp ./config-files/wpa_supplicant.conf /etc/wpa_supplicant/wpa_supplicant.conf
chmod 444 /etc/wpa_supplicant/wpa_supplicant.conf

echo "[3/8] Configuring hostapd"
cp ./config-files/hostapd.conf /etc/hostapd
cp ./config-files/hostapd /etc/default


#############################################################
#   option for adafruit wifi adapter or any rtl871x adapter
#############################################################

mv /usr/sbin/hostapd /usr/sbin/hostapd.ORIG
echo "[4/8] Adafruit hostapd binary copied"
cp ./hostapd-adafruit /usr/sbin/hostapd
cp ./config-files/hostapd-adafruit.conf /etc/hostapd/hostapd.conf
chmod 755 /usr/sbin/hostapd



echo "[5/8] Configuring NAT"
cp ./config-files/sysctl.conf /etc

echo "[6/8] Configuring iptables"
cp ./config-files/iptables.ipv4.nat /etc

touch /var/lib/misc/udhcpd.leases

echo "[7/8] Initialising access point"
service hostapd start
update-rc.d hostapd enable

echo "[8/8] Initialising DHCP server"
service udhcpd start
update-rc.d udhcpd enable

echo "================================================================"
echo "=================== Configuration complete! ===================="
echo "================================================================"

echo "+++++++++++++++++  REBOOTING in 5 SECONDS  ++++++++++++++++++++"
echo "++++++++++++++++++++++ CTL-C to cancel ++++++++++++++++++++++++"

sleep 5
reboot

exit 0